version: "3.8"

services:
  java-app:
      image: meghrajfand8788/java-app:latest
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "8000:8000"  # Maps host port 8000 to container port 8000
    restart: always
